-- MySQL Script generated by MySQL Workbench
-- sre 28 dec 2016 11:41:17 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `IdUsers` INT NOT NULL,
  `Role` INT NOT NULL,
  `NameU` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) BINARY NOT NULL,
  `Street` VARCHAR(45) NULL,
  `StreetNum` VARCHAR(45) NULL,
  `City` VARCHAR(45) NULL,
  `Postcode` INT NULL,
  `Country` VARCHAR(45) NULL,
  `Phone` INT NULL,
  PRIMARY KEY (`IdUsers`))
ENGINE = ndbcluster;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `IdProducts` INT NOT NULL,
  `NameP` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Date` DATE NOT NULL,
  `Price` FLOAT NOT NULL,
  `Image` VARCHAR(45) NOT NULL,
  `Active` TINYINT(1) NOT NULL,
  `Users_IdUsers` INT NOT NULL,
  PRIMARY KEY (`IdProducts`, `Users_IdUsers`),
  INDEX `fk_Products_Users1_idx` (`Users_IdUsers` ASC),
  CONSTRAINT `fk_Products_Users1`
    FOREIGN KEY (`Users_IdUsers`)
    REFERENCES `mydb`.`Users` (`IdUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `IdOrders` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Status` INT NULL,
  `Users_IdUsers` INT NOT NULL,
  `Products_IdProducts` INT NOT NULL,
  PRIMARY KEY (`IdOrders`, `Users_IdUsers`, `Products_IdProducts`),
  INDEX `fk_Orders_Users_idx` (`Users_IdUsers` ASC),
  INDEX `fk_Orders_Products1_idx` (`Products_IdProducts` ASC),
  CONSTRAINT `fk_Orders_Users`
    FOREIGN KEY (`Users_IdUsers`)
    REFERENCES `mydb`.`Users` (`IdUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Products1`
    FOREIGN KEY (`Products_IdProducts`)
    REFERENCES `mydb`.`Products` (`IdProducts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
